### ISSUE TITLE
Can you reload code without rebooting server?

### ISSUE THREAD

**Issue by PsuFan** [artex-development/docs.lukkit.net#2]
Can you reload code without rebooting server? I used an lua plugin for a different game and the best feature it had was the ability to reload/compile the lua code without restarting the game. Is there a way to do this with lukkit?

**Comment by jupjohn** [comment]
You should be able to reload the server using ``/reload`` and it should reload lukkit plugins. All variables and the plugin's current state will be lost

**Comment by jupjohn** [comment]
v3 is looking at having hot-reloading capabilities, but that's in the works (and has been for a good amount of time, sorry)
